# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "hugo"
type = "cli"

[platform.macos]
download-file = "hugo_{version}_darwin-universal.tar.gz"

[platform.dragonfly]
download-file = "hugo_{version}_dragonfly-amd64.tar.gz"

[platform.freebsd]
download-file = "hugo_{version}_freebsd-amd64.tar.gz"

[platform.linux]
download-file = "hugo_{version}_linux-{arch}.tar.gz"

[platform.netbsd]
download-file = "hugo_{version}_netbsd-amd64.tar.gz"

[platform.openbsd]
download-file = "hugo_{version}_openbsd-amd64.tar.gz"

[platform.solaris]
download-file = "hugo_{version}_solaris-amd64.tar.gz"

[platform.windows]
download-file = "hugo_{version}_windows-{arch}.zip"

[install]
checksum-url = "https://github.com/gohugoio/hugo/releases/download/v{version}/hugo_{version}_checksums.txt"
download-url = "https://github.com/gohugoio/hugo/releases/download/v{version}/{download_file}"

[install.arch]
x64 = "amd64"
x86_64 = "amd64"
arm = "arm"
aarch64 = "arm64"

[install.primary]
exe-path = "hugo"

[resolve]
git-url = "https://github.com/gohugoio/hugo"
