# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "zola"
type = "cli"

[platform.linux]
download-file = "zola-v{version}-x86_64-unknown-linux-gnu.tar.gz"

[platform.macos]
download-file = "zola-v{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
download-file = "zola-v{version}-x86_64-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/getzola/zola/releases/download/v{version}/{download_file}"

[install.primary]
exe-path = "zola"

[resolve]
git-url = "https://github.com/getzola/zola"
